version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: flask_api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/eshop_db

  frontend:
    build: ./frontend
    container_name: web_client
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
